"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./Provider";
import { RecoilRoot } from "recoil";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Instagram clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <RecoilRoot>{children}</RecoilRoot>
        </NextAuthProvider>
      </body>
    </html>
  );
}
